// src/components/Contact.vue
<template>
  <div>
    <section class="w-full py-32" id="contact">
      <div class="container mx-auto">
        <div class="text-center max-w-xs md:max-w-2xl mx-auto">
          <h2
            class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl"
          >
            Get in Touch
          </h2>
          <p class="mt-4 text-lg leading-6 text-gray-400">
            Although I am not currently accepting new projects at this time,
            feel free to shoot me an email and I will be sure to get back to you
            when my schedule opens up!
          </p>
          <div class="text-center mt-10">
            <a
              href="mailto:jaralato@gmail.com"
              class="inline-flex items-center px-6 py-3 border border-transparent shadow-sm text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Message Me
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 ml-3 text-white"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"
                />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
import Vue from "vue";

export default Vue.extend({
  name: "Contact",
  components: {}
});
</script>

// src/components/Contact.tsx
import VisibilitySensor from "react-visibility-sensor";
import { useAtom } from "jotai";
import { tabAtom } from "../atoms";

const Contact: React.FC = () => {
  const [, setTab] = useAtom(tabAtom);

  function onChange(isVisible: boolean) {
    if (isVisible) setTab("Contact");
  }
  return (
    <>
      <VisibilitySensor onChange={onChange}>
        <div
          className="container mx-auto flex min-h-screen flex-col justify-center gap-12 px-4 py-16  text-center lg:pr-64 lg:text-left"
          id="Contact"
        >
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Get in Touch.
          </h1>
          <p className="text-2xl text-white">
            Feel free to shoot me an email anytime!
          </p>
          <div className="flex items-center justify-center gap-5 text-[hsl(280,100%,70%)] lg:justify-start">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="h-6 w-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"
              />
            </svg>

            <a
              href="mailto:hi@jacoblatona.com"
              className="flex items-center text-2xl"
            >
              hi@jacoblatona.com
            </a>
          </div>
        </div>
      </VisibilitySensor>
    </>
  );
};

export default Contact;
